name: CI

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Build
      - uses: actions/checkout@v3
      - name: Build all
        run: make build-all

      # Upload artifacts
      - name: Upload typioca-win-amd64
        uses: actions/upload-artifact@v3
        with:
          name: typioca-win-amd64
          path: execs/typioca-win-amd64.exe
      - name: Upload typioca-win-arm64
        uses: actions/upload-artifact@v3
        with:
          name: typioca-win-arm64
          path: execs/typioca-win-arm64.exe
      - name: Upload typioca-linux-amd64
        uses: actions/upload-artifact@v3
        with:
          name: typioca-linux-amd64
          path: execs/typioca-linux-amd64
      - name: Upload typioca-mac-amd64
        uses: actions/upload-artifact@v3
        with:
          name: typioca-mac-amd64
          path: execs/typioca-mac-amd64
      - name: Upload typioca-mac-arm64
        uses: actions/upload-artifact@v3
        with:
          name: typioca-mac-arm64
          path: execs/typioca-mac-arm64

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: execs
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: typioca ${{ steps.get_version.outputs.version }}
          files: execs/**/*
  winget:
    needs: release
    runs-on: windows-latest # Action can only be run on Windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: bloznelis.typioca
          version: ${{ github.ref_name }}
          token: ${{ secrets.WINGET_TOKEN }}
